CREATE TABLE "Merchant" (
  "id" TEXT PRIMARY KEY, "slug" TEXT NOT NULL UNIQUE, "name" TEXT NOT NULL,
  "nameZh" TEXT NOT NULL DEFAULT '', "category" TEXT NOT NULL DEFAULT '',
  "country" TEXT NOT NULL DEFAULT '', "region" TEXT NOT NULL DEFAULT '',
  "description" TEXT NOT NULL DEFAULT '', "website" TEXT NOT NULL DEFAULT '',
  "phone" TEXT NOT NULL DEFAULT '', "email" TEXT NOT NULL DEFAULT '',
  "logo" TEXT NOT NULL DEFAULT '', "image" TEXT NOT NULL DEFAULT '', "sourceUrl" TEXT NOT NULL DEFAULT '',
  "version" INTEGER NOT NULL DEFAULT 1, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL
);
ALTER TABLE "Store" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN "merchantId" TEXT, ADD COLUMN "outletName" TEXT, ADD COLUMN "city" TEXT,
  ADD COLUMN "address" TEXT, ADD COLUMN "hours" TEXT, ADD COLUMN "phone" TEXT,
  ADD COLUMN "email" TEXT, ADD COLUMN "image" TEXT, ADD COLUMN "reviewUrl" TEXT;
ALTER TABLE "Store" ADD CONSTRAINT "Store_merchantId_fkey" FOREIGN KEY ("merchantId") REFERENCES "Merchant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
